### PR TITLE
animation remove starred feat added memory leak fix date fromat

### LINKED ISSUE #7: Starred notes

### PR DESCRIPTION
**Pull request by abhishek-jain-1999**
animation remove
starred feat added
memory leak fix
date fromat

### CODE REVIEW

File: lib/ui/all_notes.dart [hunk 1]
```diff
@@ -17,7 +17,9 @@ import 'package:shared_preferences/shared_preferences.dart';
 import '../model/url_builder.dart';
 
 class AllNotes extends StatefulWidget {
-  const AllNotes({Key? key}) : super(key: key);
+  final bool starredFragment;
+
+  const AllNotes({Key? key,required this.starredFragment}) : super(key: key);
```
Comment (singaltanmay) [inline lib/ui/all_notes.dart:22]: Starred Notes ke liye alag widget bana

File: lib/widgets/app_bottom_navigation_bar.dart [hunk 2]
```diff
@@ -32,15 +32,21 @@ class _AppBottomNavigationBarState extends State<AppBottomNavigationBar> {
           switch (value) {
             case Constants.appBarHomePosition:
               Navigator.pushReplacement(context,
-                  MaterialPageRoute(builder: (context) => const AllNotes()));
+                  PageRouteBuilder(
```
Comment (singaltanmay) [inline lib/widgets/app_bottom_navigation_bar.dart:35]: Why are you using PageRouteBuilder?

File: lib/widgets/note_list_tile.dart [hunk 3]
```diff
@@ -52,6 +57,15 @@ class NoteListTile extends StatefulWidget {
 }
 
 class _NoteListTileState extends State<NoteListTile> {
+
+  late bool isStarred;
+
+  @override
+  void initState() {
+    super.initState();
+    isStarred = widget.note.starred;
```
Comment (singaltanmay) [inline lib/widgets/note_list_tile.dart]: why on initState? This can be done during build

**Review by singaltanmay — CHANGES_REQUESTED** [review]
Changes are required. In the future, break out different features such as starred note and url token query param into different PRs by creating new branches
